<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLbSoTfX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLbSoTfX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLbSoTfX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLbSoTfX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLbSoTfX\App_KernelDevDebugContainer([
    'container.build_hash' => 'LbSoTfX',
    'container.build_id' => '9dd46037',
    'container.build_time' => 1679853387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLbSoTfX');
