<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGvp92aE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGvp92aE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGvp92aE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGvp92aE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGvp92aE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gvp92aE',
    'container.build_id' => '960536c4',
    'container.build_time' => 1679488064,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGvp92aE');
