<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlU4x1w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlU4x1w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHlU4x1w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHlU4x1w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHlU4x1w\App_KernelDevDebugContainer([
    'container.build_hash' => 'HlU4x1w',
    'container.build_id' => '200d5a13',
    'container.build_time' => 1679775509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlU4x1w');
